a=int(input("Enter a value: "))
b=int(input("Enter another value: "))
print("ADDITION:",a+b)
print("SUBTRACTION:",a-b) 
print("MULTIPLICATION:",a*b)
print("DIVISION:",a/b)
print("MODULUS:",a%b)
print("EXPONENTIATION:",a**b)
print("FLOOR DIVISION:",a//b)