a=int(input("FIRST VALUE:"))
b=int(input("SECOND VALUE:"))
print("a==b:",a==b)
print("a!=b:",a!=b)
print("a>b:",a>b)
print("a<b:",a<b)
print("a>=b:",a>=b)
print("a<=b:",a<=b)
print("a is b:",a is b)
print("a and b:",a and b)
print("a or b:",a or b)
print("not a:",not a)
print("not b:",not b)
print("a & b:",a & b)
print("a | b:",a | b)
print("a ^ b:",a ^ b)
